@file:Suppress("unused")

package tables

class CodonHashMaps {

    /* Generated file from TheGeneticCodeNCBI.kt */

    val codonTables: MutableList<HashMap<String, Char>> = mutableListOf(
        hashMapOf(  /* Table 1 The Standard Code */
            Pair("TTT", 'F'),
            Pair("TTC", 'F'),
            Pair("TTA", 'L'),
            Pair("TTG", 'L'),
            Pair("TCT", 'S'),
            Pair("TCC", 'S'),
            Pair("TCA", 'S'),
            Pair("TCG", 'S'),
            Pair("TAT", 'Y'),
            Pair("TAC", 'Y'),
            Pair("TAA", '*'),
            Pair("TAG", '*'),
            Pair("TGT", 'C'),
            Pair("TGC", 'C'),
            Pair("TGA", '*'),
            Pair("TGG", 'W'),
            Pair("CTT", 'L'),
            Pair("CTC", 'L'),
            Pair("CTA", 'L'),
            Pair("CTG", 'L'),
            Pair("CCT", 'P'),
            Pair("CCC", 'P'),
            Pair("CCA", 'P'),
            Pair("CCG", 'P'),
            Pair("CAT", 'H'),
            Pair("CAC", 'H'),
            Pair("CAA", 'Q'),
            Pair("CAG", 'Q'),
            Pair("CGT", 'R'),
            Pair("CGC", 'R'),
            Pair("CGA", 'R'),
            Pair("CGG", 'R'),
            Pair("ATT", 'I'),
            Pair("ATC", 'I'),
            Pair("ATA", 'I'),
            Pair("ATG", 'M'),
            Pair("ACT", 'T'),
            Pair("ACC", 'T'),
            Pair("ACA", 'T'),
            Pair("ACG", 'T'),
            Pair("AAT", 'N'),
            Pair("AAC", 'N'),
            Pair("AAA", 'K'),
            Pair("AAG", 'K'),
            Pair("AGT", 'S'),
            Pair("AGC", 'S'),
            Pair("AGA", 'R'),
            Pair("AGG", 'R'),
            Pair("GTT", 'V'),
            Pair("GTC", 'V'),
            Pair("GTA", 'V'),
            Pair("GTG", 'V'),
            Pair("GCT", 'A'),
            Pair("GCC", 'A'),
            Pair("GCA", 'A'),
            Pair("GCG", 'A'),
            Pair("GAT", 'D'),
            Pair("GAC", 'D'),
            Pair("GAA", 'E'),
            Pair("GAG", 'E'),
            Pair("GGT", 'G'),
            Pair("GGC", 'G'),
            Pair("GGA", 'G'),
            Pair("GGG", 'G')
        ),
        hashMapOf(  /* Table 2 The Vertebrate Mitochondrial Code */
            Pair("TTT", 'F'),
            Pair("TTC", 'F'),
            Pair("TTA", 'L'),
            Pair("TTG", 'L'),
            Pair("TCT", 'S'),
            Pair("TCC", 'S'),
            Pair("TCA", 'S'),
            Pair("TCG", 'S'),
            Pair("TAT", 'Y'),
            Pair("TAC", 'Y'),
            Pair("TAA", '*'),
            Pair("TAG", '*'),
            Pair("TGT", 'C'),
            Pair("TGC", 'C'),
            Pair("TGA", 'W'),
            Pair("TGG", 'W'),
            Pair("CTT", 'L'),
            Pair("CTC", 'L'),
            Pair("CTA", 'L'),
            Pair("CTG", 'L'),
            Pair("CCT", 'P'),
            Pair("CCC", 'P'),
            Pair("CCA", 'P'),
            Pair("CCG", 'P'),
            Pair("CAT", 'H'),
            Pair("CAC", 'H'),
            Pair("CAA", 'Q'),
            Pair("CAG", 'Q'),
            Pair("CGT", 'R'),
            Pair("CGC", 'R'),
            Pair("CGA", 'R'),
            Pair("CGG", 'R'),
            Pair("ATT", 'I'),
            Pair("ATC", 'I'),
            Pair("ATA", 'M'),
            Pair("ATG", 'M'),
            Pair("ACT", 'T'),
            Pair("ACC", 'T'),
            Pair("ACA", 'T'),
            Pair("ACG", 'T'),
            Pair("AAT", 'N'),
            Pair("AAC", 'N'),
            Pair("AAA", 'K'),
            Pair("AAG", 'K'),
            Pair("AGT", 'S'),
            Pair("AGC", 'S'),
            Pair("AGA", '*'),
            Pair("AGG", '*'),
            Pair("GTT", 'V'),
            Pair("GTC", 'V'),
            Pair("GTA", 'V'),
            Pair("GTG", 'V'),
            Pair("GCT", 'A'),
            Pair("GCC", 'A'),
            Pair("GCA", 'A'),
            Pair("GCG", 'A'),
            Pair("GAT", 'D'),
            Pair("GAC", 'D'),
            Pair("GAA", 'E'),
            Pair("GAG", 'E'),
            Pair("GGT", 'G'),
            Pair("GGC", 'G'),
            Pair("GGA", 'G'),
            Pair("GGG", 'G')
        )
    )

}