@file:Suppress(
    "UNUSED_VARIABLE", "MemberVisibilityCanBePrivate", "UNUSED_PARAMETER", "unused",
    "ReplaceManualRangeWithIndicesCalls"
)

import algorithms.OverlapGraphsOofN
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import kotlin.test.assertContentEquals

/**
 * See also:
 * http://rosalind.info/problems/grph/
 * Overlap Graphs
 *
 * Problem

A graph whose nodes have all been labeled can be represented by an
adjacency list, in which each row of the list contains the two node
labels corresponding to a unique edge.

A directed graph (or digraph) is a graph containing directed edges,
each of which has an orientation. That is, a directed edge is represented by
an arrow instead of a line segment; the starting and ending nodes of an
edge form its tail and head, respectively. The directed edge with tail v
and head w is represented by (v,w) (but not by (w,v)). A directed
loop is a directed edge of the form (v,v)

For a collection of strings and a positive integer k, the overlap graph
for the strings is a directed graph Ok in which each string is represented
by a node, and string s is connected to string t with a directed edge when
there is a length k suffix of s that matches a length k prefix of t, as
long as s≠t; we demand s≠t to prevent directed loops in the overlap graph
(although directed cycles may be present).

Given: A collection of DNA strings in FASTA format having total length at most 10 kbp.

Return: The adjacency list corresponding to O3. You may return edges in any order.

KEY HERE is O3 - three characters must match in prefix and suffix!
 */

internal class RosieOverlapGraphTest {

    lateinit var overlapGraphs: OverlapGraphsOofN
    lateinit var u: Utility

    @BeforeEach
    fun setUp() {
        overlapGraphs = OverlapGraphsOofN()
        u = Utility()
    }

    @AfterEach
    fun tearDown() {
    }

    @Test
    @DisplayName("Rosalind Rna Splicing sample test")
    fun rosalindOverlapGraphSampleTest() {
        val sampleInput = """
>Rosalind_0498
AAATAAA
>Rosalind_2391
AAATTTT
>Rosalind_2323
TTTTCCC
>Rosalind_0442
AAATCCC
>Rosalind_5013
GGGTGGG
        """.trimIndent().lines()

        val overlapN = 3

        val expectedResult = """
Rosalind_0498 Rosalind_2391
Rosalind_0498 Rosalind_0442
Rosalind_2391 Rosalind_2323
        """.trimIndent().lines()

        /*
         * set up the lookup of the results back to the origina strings
         */

        val dnaList = u.utilityParseFASTA(sampleInput).toMutableList()

        val dnaString = dnaList[0]

        val hashMapResult = overlapGraphs.overlappingPrefixAndSuffix(overlapN, dnaList)

        //println(hashMapResult)

        val resultsList: MutableList<String> = mutableListOf()
        for (s in hashMapResult) {
            for (l in hashMapResult[s.key]!!) {
                val fromName = u.stringToNameMap[s.key]
                val toName = u.stringToNameMap[l]
//                println("$fromName $toName")
                resultsList.add("$fromName $toName")
            }
        }

        assertContentEquals(expectedResult, resultsList)

    }

    @Test
    @DisplayName("Rosalind Rna Splicing Quiz test")
    fun rosalindOverlapGraphQuizTest() {
        val sampleInput = """
>Rosalind_9140
GCGTCGATGTTTCGAAGCGATGCCAATTCGCATCTGGGTCCGAGACCAAATGGTCCTTAT
AACTCTGGTAATTTAGGTACAATCGATGTGCGGT
>Rosalind_1217
GTTATAACGATGCCGGCTTGCTGGTCATGACCATGGTTCACGACGTGCGGTTGGGCGTCG
TCGCGCGATAGACTAAACCCGTAGGAGAAGCTGGGTGCG
>Rosalind_5304
CGATGGACGGCAATTCTCGCTCGGGTTGACAGCTCCTGGTTCTAAACCACCTCGGGAAAT
ATCACTATCCTGCCAAGCGCTCCGACAACCC
>Rosalind_4376
CGACTGGGAATGTTCGCAGGTTGTTACCTTCAGTGATGTGCAGGACACTCGAATGAGGTG
GAAGGAGGAATGACATCATCGCTAACGCGAACG
>Rosalind_9839
CAAGGGAGTGCAGCTCTGCGACTTTGGATGAGCTATCCGCCTCTGTATCTGGGCAACCAA
GAGAAGCATCGGGGTTTGCG
>Rosalind_1946
AGTATAAGAAATTGGACCCCTCCTGTAGGTGAATCAATGAAAGTTTAGTGAAAAAGATAA
GTAACGTTGTTGTCCCTCTACGCCTGACAATTCACG
>Rosalind_5975
TGTGGAGTTTGATTCAAGTCATGGCTATGAAGGACAAGGGTTCACTTGCTCAATCTCTAG
GTTTTGAGGAAGTCTAGCTAAG
>Rosalind_8095
GATTGCGGGAGACAGTTACACCTGCTATCACATATAGTTAGTAGTTGCTGCTCTCGTTCG
TGATGGCCCCGGAATCCACTGTAATCCCG
>Rosalind_1540
TGCATCAAAGAATTAGTCCTACTGACTTAGGCACTCTACTCCAGTGCACAAATCGCTCCG
TGTCGTCAGATTGCTCTGCCATGATTCTCCTCTTATT
>Rosalind_2374
CTGAAGAAGCTCTCTACTTAGGTGTGTAAAATGTACTGACAGGACCGCTGTTTAGGGGGG
GACAGTCCATCTTGTAGAACTAGCAACT
>Rosalind_4261
TTTCCTGTAGCCCGCTCAGACACAACGAACCCGTTCCGGTTAACAACTGGTCCAAACGAC
TCTAAGGGGGCAAGACCACAGCAATAGAAGATCCA
>Rosalind_8069
GCGAGTAAACTTGGTGGGCCTGAACTAACTCAGGGCGTTACAGCCCTCACTATGTGCACA
TCCACCGTCGCGCGGGGCGGAACCCCAAGCAGACCA
>Rosalind_6426
CGCTAACCATACTCAGCGGGTGCAGCTATAAGTGAATAAAATGGAGGTAGCGAGAAGTGC
CATGTCCAACTCCCCCCTTTTAG
>Rosalind_6987
ACCCACGTTATTGAAGATACGTACGATCCCCTTATTTCGGAAAAGGCCCCGGAAGCCGTA
AGGCCGCAGGAGTTCACCCTCGCG
>Rosalind_4288
GGAGGCAGATGTTACAAGGCAATATGGAATATTGTACGGGCCGTTGTTTTCAATACGCGT
CTTGCAGCTATGCGTATTCGTCGGAACTGGCG
>Rosalind_3232
TTCTGGACAAGATAACGCAGCCCCTCTGGCCACTAGGAAGGACAGTGCACGGATCACTAC
GTAGCTTGAACCATAGCCAG
>Rosalind_7915
GGGAGGTCGTTTGAGCGTAGAGTTCGTTAGTTCTGGAAACTGGTTAATCTGCGTATCCGT
TTCCGTACCCTCTCATCCTCGCACGGGTG
>Rosalind_3117
CTAACTTTCGTTGGTTCTCATAATTGACTCTTAGAGCAGAGTGAGAGCTTCTGAAAGATC
ATGTGGCTATGTAGTGAATCTCCAC
>Rosalind_5101
GTAACTGCCTACTCGCTTATGGGACCGTTAGGCAAGAAGGACGACGCCTAGCAATTTTTG
TCAAGAACGAAATGTCTGTT
>Rosalind_7682
CTTACTAGACTGAGGCGTACGATCATGTTGTGACTACACTTAGTGATCTCGACTTGTCCT
AACACTGAGTCTGCTCAGTAACTACCAA
>Rosalind_5173
GTTATTGCGTGTGCTTTCCTGGCCCGTCTGGGAAGCGCCACGGATGATCCCGATTCAGCT
CGCCTTTCAGACCAGGGTTTTTACTATACGGAAACGA
>Rosalind_7828
GAATAGACCTAAGGGGGACGAGGCCACTGCGTCCCAACGGTGACTAGGAACTTAGCATTG
AACTACACTTGACCCAAGGGATGAAAGGACCATGACAATC
>Rosalind_1895
CTGAACCGTGCTGAACGGGGAATCTTGATACCTTCACCAAACCCTTATAGTGGCTAACAT
TGTGTGAAAGGCAGGTGAAAAACGATTATTTTGC
>Rosalind_7090
CCTAATGGCGCGCATTGTGTCCGTGTAAGATGTCATTGCTATTGACTATACGGCCCTTTT
AGTTCCACGTCGTGAGCCTTT
>Rosalind_8632
TCGTTACATTCATAGGGGCGGTCGCCCATCCGGGCCAGAAGCGAGTGTGGTTTCCAACCA
CATTTGATCACACAGCAGCTAAGTTAGTGAA
>Rosalind_2931
TTGGAGAGGATCACTCTACATAGAGCGGCGCCGTATTTGGGAAAATTAGTGCTGAATTGA
GCTCGGTGAAGAAGCGGTCGGGGCAGGCCGGATA
>Rosalind_6494
GCAGCATGAAGCGAGCAGCCCCAGCTACCTTAACGGAATAGGGTTTTATCAACACGCGAG
GTCGGAGGTACAAGAAAGGATAATGAGAGAGCATGTTT
>Rosalind_0480
TAGGCAATGTGCACCACGGTGTCATTCGATTATACTAAGCTCAATATGAGCATCGGCTCT
GTTACTGTAGCTGATCTGTGAAGTGCGCGCAAA
>Rosalind_7265
ACGTCCCACGTACGGGTAGCGATACACCCCCTCAGACATGTTCAAAACCGGCGCACTCGC
AGTCAGCTGCGAGGATCCAAAACTATCCCCCTCTGCC
>Rosalind_2696
TACATCACGAAAGATACTCGGCAGAGAGAATCAGGTTTTCATCCGATGTTGTTCTCGGCA
TATTATGACGCGTACCCCCGTCTCCTTGG
>Rosalind_9443
GCCGAAACGGCAGCTGTCAATTTCGGAACTCGTCCAACTCGTCAAAGCCCCTTGTCCGTG
TGGGCGTCCTGACGTCCAGCAC
>Rosalind_5567
GGAGGCAGTTATATCCAGGCTCTGCCCCAAAACAACTAGAACATTGCTGCCGAGTGCACT
TTGGGGGAGGGACACTCTCACCTGATCCAGTACGTA
>Rosalind_4735
TCGTTGCTTCATGAGTATTCAAGCTTTAAACTGCAAATTGTATACGCAGGTCAATGGGAG
CTGACGATAATCGGGAGGACCAG
>Rosalind_6309
ATTTCTGGCCTGTATCATTGGTAGAGACCGATATCCAATCAACCAAACACGGCGTAGAGC
GTAGAGTGACTCGGGGCAAAAACT
>Rosalind_6630
AATGGGAGTGACGTAATTTTGTAAAGTAAGACTTCTTTTTTTCTTTAGAGACAGCCTTCA
ATTCCGCGTCCGAACCCTGTGCGGATCCGTCACTAATAG
>Rosalind_7797
TAGCTATACAAGCGATGTCCTCCGCTAGAGAAGGGTTATCCTCCGGACGGGCCGAAGCAT
TAGGGTTCAGGAATGGGAACTAGCTGACGCAGATTCGCG
>Rosalind_8958
TTCGAAGCTTAGAAACTGTAAATCTCTAACGTAGGATATGGAAGCTTTAACCTAAGAATT
TATGGTGAACACCGCACCCGTTAGGTTGTATCAACA
>Rosalind_3625
CTTAGCTGCAAGATACCAGACTAGCTGACCTTGTCGGTCGCGTGAGAACTGACAAGCCGT
ACAGAGCGTGACAGCGTCCTC
>Rosalind_8037
TCTTCTTGCTCTGCTCATATGAATTTTGAGGTTATCGTTTCCAGGAGCGAAGAATTCATA
CGGCCCGTTGGAGAATGTGGCAATTTCCATAAAGC
>Rosalind_7884
TGGCCGCTCATTGTATCTTACTACTTCCTTTTGTTTCCTTTATAGTCCACAGGTGAAGCG
GCTTCCGGTGTGGGACGAGCCTT
>Rosalind_4170
CATGCTTCTTTCCAAAACGCGCCGAGGTAAAGGTGCGCGCTCCAACTATTGCTTGGGGTA
TTTGAGTTGCCCTCGGGATCGCG
>Rosalind_5807
AGGATAACCAGTGAAGACAGACGACTATTCTCTCACTTAAGGCGGCCGCTCTATCGGAAT
CACGGCCCCCGGCGCTGAGAGAC
>Rosalind_7595
CCGATTGACCTGCGGTTTCAGGATTCCGGGTGCACAGAGTAATCTAACCACCGGTACGAA
TCATGTGATCGCGGGGTCCAA
>Rosalind_5881
GTTGGACCTCTTTCCACAGTACGCTCATACCGAGATAGAGCGGGTCTGTAGAGGAACGCC
ATTTCAAATTGATTTATTGCCTAAAATTGTACGCACTC
>Rosalind_8399
CCAATCCATCACTGAGAATGATCAAACGTTCACCACGAAGACTTACTGAATTTATAACCA
ATGAATTGATGTTAATCCTGTGGCTCGCGGGTGACC
>Rosalind_6809
AACCCCAGTAGAACCTTCCGGCCATGTATGGACCGAGACGCTAGAACTATTATCGGAGCC
TTATTCGTAACCCGAGACAGC
>Rosalind_5600
GCGTCTTAACTACTCTAGCTGCGGCTAAAGGTGTTATAGAAACGGCACTACGTTGCGGAT
AGCTAGTCCATTTTTACCTCTGGGGGAGATGCCAA
>Rosalind_2013
TAGTAGCCCCGTGCGTGGTACCGCAGAATATCGGCCTGACCAGCACTCGCACAAAGAGTG
CCGAAGCATAGAAATCGACCTGACTCTTGAGCCAGTCTCC
>Rosalind_9001
ACCATCCCGTCCATACGTACTAGCCAGGAGACGCCGCTTTAAACTGCGAACGCAGCAGTG
CTATGCTACCGAGAGACATGATTAAAGCGAAAT
>Rosalind_9264
TCCTAATATGACCACGCATGGGTTGCCGCGTACGGCCCCAAGCTACTTCGACCATCCGGC
CAGAGCTAAATCATTAACTCCT
>Rosalind_0760
ATTAACCGAAGCTCATTGTAAGGTTCTTTTTTGTCGTCACCAGTTTAATAGAAGTCCCGA
GGCCTGTATGCATACCCTAGATTTCGTGAAGT
>Rosalind_7453
ATATTGTTGCCGCATGTCATACTTGGATAACGCAGTCTGCACAAGTCTCCGCTGAATATG
CTTAATTTCACAATACGGGAGGCATGAGAGCCGCC
>Rosalind_2994
CAGGCAGGGTTTTATACATATCGTAGGAATCTCGGGTCGGCAAAGTAAACTGCATGCTCT
TTCTCTTTTTGGTCCTGGTACCGTAAG
>Rosalind_2154
CTTGCGGCTTTCCTCAACCCAAATGTAACCGGGTATAGAATGGCGAAGGGCATTTGGCAG
AGTGTAGTGACCTTCTCAGCTCTGCGAT
>Rosalind_1342
CGCATCGGAAACGGTACCGTAATCGAGGACGCGGCAGAGACGTTCGAATGGGAGAGAAGA
TCTGTTCTGACCACGGGGGTAGCCCCAAGTGAAGGAGTC
>Rosalind_1204
CGCTATACCAGCCGGTACGGCGGTAGTTCATTATCTGGTAGTTCGGCAGGCCCAGAGGTG
CTAGGTTCCTTCTAGGAACA
>Rosalind_3932
AACACAGGCCCTGTCGATGTCCTTTCTACTGTCTTACGGCGGATTCCATCGTCGTTCTCT
CTAAGCACGTCTAGCCCGATCCTACGGAAGTTTCGA
>Rosalind_1404
GATAGCGGAGAAAGGTTGAGAATTTTTTAGGCTGGATGCGACCGCGGGAGACCAACAAAG
GTCAAAAAGTTAGGTACTATACCCCAGCGACTTATA
>Rosalind_0237
CTATATGGTTCAATCAACCTGTTGCTAACGCATATCAGTACGCATGAGGTCCTTTAAGAT
CGCGAGGGAGTAGAGAGCTGTGCCCTTACAGCAGAAGGC
>Rosalind_4879
GGGAAGCGGTGTTGCAGTAGTTAAACGGGGGTACGCTCACTTGGCATATCACCGGTCAAC
CGCAAAGAGATCTGAGGCTGGGGACCACGGCCGGCGT
>Rosalind_4223
GCGTGTCAAATCGTCTGTGTAATGTGCCTGCCAGTCAGGCTTGGGAATCTCGCCCCCGGA
ACTTTCTCACGGATGAGGTACGTAGCGATTAGGAAGCAG
>Rosalind_1799
TAGCCCCGTCCAGATTGGCGCGTAATTGTAGGGGATGCGGTGCATTTATTCCAACACTAA
ACCAAGTATGGAATCGGTGCGTGTG
>Rosalind_9697
CTTCGGGTAGTTACACTCTTATCGACATATGAGCATGGGCCTCGACGAGAAACAGTGTCG
GTTGCGAAGATGTATCCATACTTCCGAT
>Rosalind_2655
GTACGTTAATCGTGGTGTTGGTGCCGGGCGTCGCGCAGGCAAGCCGGGTATGCGGAGCTG
TCCAGTTACCGTAGGGTCGGT
>Rosalind_5187
TCCCTTACCAGTTGCAATACCAATGATGGTCGCTGCGTTAGCTTAATCATTGACTCTGGC
GAGTAGTCCGCGATTCAGAG
>Rosalind_9994
GAGGCGAATATTACAAGATGCAATGAATATATAAGGTTGCACCGAGATTATCAACAAAGG
GCATTGGAAATGATAACATGCATC
>Rosalind_0061
AGTGTGCCCCAATCAGCCGGTAGGTCCGCGCAGGCAAATATGCAGTCACGTGGTCATGCA
TACTCGGCTAGCCGGAGGTAGTGACTTACGC
>Rosalind_9011
GCAGGCCCCAGCACGCGCATGGATTCCTGCCCCGAGGGCCCGATCTCAGGAAATACGGTT
GATCAGACCTCTGAAGACCAGGAGTGGTCG
>Rosalind_7644
GTAGATCCCAGTCGCGTTCGTCCACTCTCACCCTTGTTACCTGAAACGTGTCGAGCTGAT
GACCTCGGGAGCGCTACCATAGAGTGCGCTTCACGAGG
>Rosalind_4289
ATCTGGACCGAACTTGGACTGACAGCCGACCCTTTAGGAGGTATGTGGATTGGTATGAAA
GTTGTGTCGGCTGTAATTGT
>Rosalind_4503
ATCGCGCAGGTCAGTAGGGCGACCACATGTGTCAAAAGCCGAAACTGATTCGATCGATTT
AGGGCTTGAGTCTGCAGATTTAT
>Rosalind_1754
CCGTGCCTCACCAAATCGTCCTTTGGGACCCAGAGGGCCGCGTTGATGTCAAAGGATCCG
AGCATCTTGCTTTCCAACTTC
>Rosalind_2861
GACGGCCATCGTGCACTCGTATACCTCGTTACCAGATAGTGGGCTCTTGGTTTCGCAAAA
GAATGAAGCTATGTCCCTTGAATATATCTCGGAGCTACCT
>Rosalind_1222
AAATAATTCTGGAACTGTTCGACTTAGGCCTTAGGCTATCTCCTATCAGAGCGGACGCTA
CAACATGGCGTTGTCGCGGACTGATTTTG
>Rosalind_2397
CGTATGAGAGTTTTCTAATAGATACAGTTTTGGATACCGTCATTTATCCTGGATTGTCAC
GTTTGAGACCTTCACTGAGTTACGCCATAGGTAC
>Rosalind_9375
AGGCGAGAGGGTCAATCGCATGAACTCTTGATAAGTGCGTCCTCAGGTACCGTCGACTGA
TAGGCATTAGCTTCGGCTTATAAA
>Rosalind_9944
GGCATATTGCCAGAGAAGGCCGCACAATCTACTACTTCCTGAGATGATAGCAAAGATCTG
CTGGGATGTTTTGGACCCATTATG
>Rosalind_7783
GGCTCCTGTTATCGTATTTGCTCCCCCTCTTCAGGTCTGAGCCACTTGGGCAGGCTCTTC
TCACAGGGTGAAATCGATCAGTTAGTAT
>Rosalind_3325
CACTGTGTCTGGCTTCGGTAGTGAGGACTGACTGGGACCTCGAAAATCACTGGCCTTTGT
ACTCAGTGAACCAGTGCGAAGCA
>Rosalind_3993
GGATATAGCAGTTCGTATTTGTTAGAATATAAGCGCCAGGAGGAAACAGTAAGCTAAGGC
AGAGGAGACCATGCAGCTGGTGATT
>Rosalind_9397
TTAATCAAACCCTAACGACTGAATTCCCCAAAAGATGCCGTGCCTACCACACCATCGTTG
ATCATGCGCTCCAACCATCGAA
>Rosalind_4672
AACGATATTCCTCCCGAGGATCGGCACTCCTTTCAGTGCGGGGATCGCTTGCTATGACCT
CTCGCCTACGGGGGAAGGCAAATTC
>Rosalind_8243
ATCAGTGACGAGTCTCCACCAATGCATTAGATGATTACTCTTCATTGTTTCGCGGTGTAG
AGTTACCCGTCGTGAAGGATAGCTGT
>Rosalind_8878
TTCGGTGAAACCCTTTTACAGGTCACATGCGCGAGCGGCGTTAAACTGAACAGACCTTTG
CTTACTTGTTACTACGGAGGCAGAAAGACAAC
>Rosalind_0429
TGCGAACTGGATTTACGAAAATGGATATATTCAGTTTAGCAAACAGTATCATTTCTTAGA
TAGATTCTGCTATCAGTTAGGG
>Rosalind_8080
CGTAGAGTCTAATAATGACTCGCCCGAATAAAATTCGTGTGTATTACTTGATGACTAACC
TTGCATTACACAATAGTTACTTCGGTCACGC
>Rosalind_7580
TACGGGTCCTATGTGTCTGTGTGGTCATGCCAAAGTTTCCATGTGGAAGCTTTGCCGTAT
CAACGGTATTTCTCCTTGTTTTTCAGAGGGAAATTGAC
>Rosalind_9673
TTATCTACGGCCTCTAACGTACTATGCTGCGTAGGCGGATGCACCACTGCGAGCTGCCCA
AAGCTGACGCTGTAGTAACGCCAAG
>Rosalind_5832
TCGTGTTAGCTATAGTATATAGCGGACTCACGTACTTAAACCCCTCACCGGCATGCATAA
GCAGGCCGTACGGTTGTGACTTTAGTCCTGGTGCCGTAA
>Rosalind_2697
GCGTTGCGGCGACCTCTCGGTGCCCGCACCAGTGCACCGAAACTGGGACATTTGTGTCGC
AACACTACAGTCAGCAATAAAGGCAGGTGGGCCTGCCGAG
>Rosalind_7576
GCATACCGCCCAAACTTCTAACTCCTCCTGCGAAACTGGTAGTCCTACTTGCAGTTCGAT
AAACAGAGACCTATAATCGAATGACGTCCTTA
>Rosalind_6614
TTTACCCCTCTCGATCACGACCGTGAAGCAGGACACCGGGCCTACCTAGACGTCGACGAT
GACCTTTAGATTTTTCGATACTACGACGGGACCATCCCT
>Rosalind_4595
GACCACTGCGTGCGGTATAGAGGAACTTCATGCTTCGGCCACAATGTCGCGGTCTCGAAG
TTGGAGCGACTGCCCATATCCT
>Rosalind_9615
AATCGGGTTTACCTCGCCCTCGAATTGAACTCAGAATAAATGTTATATACGGCCGTTCTA
CAACTAGATTATGTAACTAGCCTGGACGCGCAGTTTCTGT
>Rosalind_3154
TAGGGAAGTACACCGTAATGAGCCATTGTCGAGCAACCTCATATCTGTCACAAGAGGGCT
GACCGTTTTAGGTTTAAAAACGTA
>Rosalind_9939
CTCATACGGGGCGGAACGCAAGTAGGTATTTCGCCCACAAAGATATGATCCTGGGCTAGG
TCTGCTGAAGCGTGGTAATTAGGAAGTTGCTGAGC
>Rosalind_3522
TGGCGTGGAAAGTTATACACACAAGGTGAAAACTGGAGTTAGCGGACCCGCGTGTGATAC
AAGTGTCACATTCTGGATCAAC
>Rosalind_2327
GCAGCAAGCTACTCAACTGGTTTGAGGTGTCTCCACGGGCACTCGCCTCAGTCCTGAAAC
CCTGTAAATCAAGGCTAGCTGGGCAGCGTCT
>Rosalind_7342
AATGCTCCACGACGGGCGAACACTGAAACTTTCGAGTTAAATAACCGCACCTCTCAGCGG
ATTCGCTTTACCCGATCAGAACG
>Rosalind_8285
TACTTCTTTGGTATTCCAACCGGAAATACATAGAGGTTTAACTTCTCGGCCCCGGCTCCG
GTGTGCGTGGCGCGTACAAGGGACAAAATATCT
        """.trimIndent().lines()

        val overlapN = 3

        val expectedResult = """
Rosalind_2696 Rosalind_7884
Rosalind_2696 Rosalind_3522
Rosalind_7682 Rosalind_9839
Rosalind_3117 Rosalind_3325
Rosalind_2327 Rosalind_8037
Rosalind_4223 Rosalind_2994
Rosalind_3325 Rosalind_6494
Rosalind_3325 Rosalind_9011
Rosalind_3325 Rosalind_7576
Rosalind_3325 Rosalind_2327
Rosalind_1895 Rosalind_1540
Rosalind_1895 Rosalind_0429
Rosalind_7576 Rosalind_9397
Rosalind_7576 Rosalind_9673
Rosalind_1404 Rosalind_7453
Rosalind_7453 Rosalind_9443
Rosalind_9375 Rosalind_1222
Rosalind_4288 Rosalind_9140
Rosalind_4288 Rosalind_8069
Rosalind_4288 Rosalind_5600
Rosalind_4288 Rosalind_4223
Rosalind_4288 Rosalind_2697
Rosalind_0061 Rosalind_6426
Rosalind_0061 Rosalind_1342
Rosalind_0061 Rosalind_1204
Rosalind_3154 Rosalind_5101
Rosalind_3154 Rosalind_2655
Rosalind_3154 Rosalind_7644
Rosalind_0480 Rosalind_1222
Rosalind_4170 Rosalind_9140
Rosalind_4170 Rosalind_8069
Rosalind_4170 Rosalind_5600
Rosalind_4170 Rosalind_4223
Rosalind_4170 Rosalind_2697
Rosalind_1754 Rosalind_3232
Rosalind_1754 Rosalind_8958
Rosalind_1754 Rosalind_8878
Rosalind_2861 Rosalind_7090
Rosalind_0760 Rosalind_1946
Rosalind_0760 Rosalind_0061
Rosalind_3522 Rosalind_6809
Rosalind_3522 Rosalind_3932
Rosalind_3522 Rosalind_4672
Rosalind_2397 Rosalind_2696
Rosalind_2397 Rosalind_7580
Rosalind_2397 Rosalind_8285
Rosalind_7797 Rosalind_9140
Rosalind_7797 Rosalind_8069
Rosalind_7797 Rosalind_5600
Rosalind_7797 Rosalind_4223
Rosalind_7797 Rosalind_2697
Rosalind_4672 Rosalind_3232
Rosalind_4672 Rosalind_8958
Rosalind_4672 Rosalind_8878
Rosalind_9615 Rosalind_5975
Rosalind_8878 Rosalind_6809
Rosalind_8878 Rosalind_3932
Rosalind_8878 Rosalind_4672
Rosalind_2931 Rosalind_7453
Rosalind_9839 Rosalind_9140
Rosalind_9839 Rosalind_8069
Rosalind_9839 Rosalind_5600
Rosalind_9839 Rosalind_4223
Rosalind_9839 Rosalind_2697
Rosalind_8080 Rosalind_6426
Rosalind_8080 Rosalind_1342
Rosalind_8080 Rosalind_1204
Rosalind_7828 Rosalind_4289
Rosalind_7828 Rosalind_4503
Rosalind_7828 Rosalind_8243
Rosalind_9397 Rosalind_7828
Rosalind_4289 Rosalind_5975
Rosalind_8285 Rosalind_8037
Rosalind_9443 Rosalind_3325
Rosalind_5187 Rosalind_9994
Rosalind_3932 Rosalind_5304
Rosalind_3932 Rosalind_4376
Rosalind_4879 Rosalind_2397
Rosalind_4879 Rosalind_8080
Rosalind_6494 Rosalind_4261
Rosalind_6494 Rosalind_6614
Rosalind_6426 Rosalind_0480
Rosalind_6426 Rosalind_7797
Rosalind_6426 Rosalind_2013
Rosalind_6426 Rosalind_1799
Rosalind_6426 Rosalind_3154
Rosalind_6614 Rosalind_7090
Rosalind_7265 Rosalind_9443
Rosalind_5173 Rosalind_5304
Rosalind_5173 Rosalind_4376
Rosalind_7644 Rosalind_5807
Rosalind_7644 Rosalind_9375
Rosalind_6987 Rosalind_9140
Rosalind_6987 Rosalind_8069
Rosalind_6987 Rosalind_5600
Rosalind_6987 Rosalind_4223
Rosalind_6987 Rosalind_2697
Rosalind_5101 Rosalind_1217
Rosalind_5101 Rosalind_5173
Rosalind_5101 Rosalind_5881
Rosalind_9697 Rosalind_8095
Rosalind_9697 Rosalind_1404
Rosalind_3625 Rosalind_9939
Rosalind_8632 Rosalind_7828
Rosalind_9001 Rosalind_6630
Rosalind_9001 Rosalind_9615
Rosalind_9001 Rosalind_7342
Rosalind_7884 Rosalind_7682
Rosalind_7884 Rosalind_3625
Rosalind_7884 Rosalind_2154
Rosalind_7884 Rosalind_9697
Rosalind_8399 Rosalind_6987
Rosalind_8399 Rosalind_9001
Rosalind_5600 Rosalind_9839
Rosalind_1946 Rosalind_7265
Rosalind_9011 Rosalind_8632
Rosalind_9011 Rosalind_4735
Rosalind_9011 Rosalind_5832
Rosalind_4261 Rosalind_8399
Rosalind_9264 Rosalind_7090
Rosalind_4735 Rosalind_2994
Rosalind_1217 Rosalind_9140
Rosalind_1217 Rosalind_8069
Rosalind_1217 Rosalind_5600
Rosalind_1217 Rosalind_4223
Rosalind_1217 Rosalind_2697
Rosalind_3232 Rosalind_2994
Rosalind_2697 Rosalind_9994
Rosalind_2154 Rosalind_8095
Rosalind_2154 Rosalind_1404
Rosalind_7580 Rosalind_2861
Rosalind_7580 Rosalind_4595
Rosalind_4595 Rosalind_7090
Rosalind_5567 Rosalind_5101
Rosalind_5567 Rosalind_2655
Rosalind_5567 Rosalind_7644
Rosalind_7090 Rosalind_4261
Rosalind_7090 Rosalind_6614
Rosalind_8095 Rosalind_7595
Rosalind_8095 Rosalind_1754
Rosalind_7342 Rosalind_7265
Rosalind_4376 Rosalind_7265
Rosalind_5807 Rosalind_2861
Rosalind_5807 Rosalind_4595
Rosalind_2013 Rosalind_9264
Rosalind_2013 Rosalind_5187
Rosalind_0237 Rosalind_9944
Rosalind_0237 Rosalind_7783
Rosalind_0429 Rosalind_7915
Rosalind_0429 Rosalind_4879
Rosalind_1540 Rosalind_6309
Rosalind_1540 Rosalind_0760
Rosalind_1222 Rosalind_2931
Rosalind_3993 Rosalind_6309
Rosalind_3993 Rosalind_0760
Rosalind_8243 Rosalind_5975
Rosalind_5881 Rosalind_9939
Rosalind_8069 Rosalind_8399
Rosalind_6630 Rosalind_0480
Rosalind_6630 Rosalind_7797
Rosalind_6630 Rosalind_2013
Rosalind_6630 Rosalind_1799
Rosalind_6630 Rosalind_3154
Rosalind_9994 Rosalind_4289
Rosalind_9994 Rosalind_4503
Rosalind_9994 Rosalind_8243
Rosalind_7595 Rosalind_9839
        """.trimIndent().lines()

        /*
         * set up the lookup of the results back to the origina strings
         */

        val dnaList = u.utilityParseFASTA(sampleInput).toMutableList()

        val dnaString = dnaList[0]

        val hashMapResult = overlapGraphs.overlappingPrefixAndSuffix(overlapN, dnaList)

        //println(hashMapResult)

        val resultsList: MutableList<String> = mutableListOf()
        for (s in hashMapResult) {
            for (l in hashMapResult[s.key]!!) {
                val fromName = u.stringToNameMap[s.key]
                val toName = u.stringToNameMap[l]
//                println("$fromName $toName")
                resultsList.add("$fromName $toName")
            }
        }

        assertContentEquals(expectedResult, resultsList)
    }


}