import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import algorithms.mostProbableKmer

/**

Given a profile matrix Profile, we can evaluate the probability of every k-mer
in a string Text and find a Profile-most probable k-mer in Text, i.e.,
a k-mer that was most likely to have been generated by Profile among all k-mers in Text.
For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT.
Indeed, every other 12-mer in this string has probability 0.
In general, if there are multiple Profile-most probable k-mers in Text,
then we select the first such k-mer occurring in Text.

Profile-most Probable k-mer Problem: Find a Profile-most probable k-mer in a string.

Input: A string Text, an integer k, and a 4 × k matrix Profile.
Output: A Profile-most probable k-mer in Text.

Code Challenge: Solve the Profile-most Probable k-mer Problem.

 * See also:
 * stepik: @link: https://stepik.org/lesson/240241/step/3?unit=212587
 * rosalind: @link: http://rosalind.info/problems/ba2c/
 */

internal class S02c05p03MostProbableKmerTest {

    @BeforeEach
    fun setUp() {
    }

    @AfterEach
    fun tearDown() {
    }

    @Test
    @DisplayName("test mostProbableKmer 1")
    fun testMostProbableKmer() {

        val genome = "TGCCCGAGCTATCTTATGCGCATCGCATGCGGACCCTTCCCTAGGCTTGTCGCAAGCCATTATCCTGGGCGCTAGTTGCGCGAGTATTGTCAGACCTGATGACGCTGTAAGCTAGCGTGTTCAGCGGCGCGCAATGAGCGGTTTAGATCACAGAATCCTTTGGCGTATTCCTATCCGTTACATCACCTTCCTCACCCCTA"
        val probString = """
            0.364 0.333 0.303 0.212 0.121 0.242
            0.182 0.182 0.212 0.303 0.182 0.303
            0.121 0.303 0.182 0.273 0.333 0.303
            0.333 0.182 0.303 0.212 0.364 0.152
        """.trimIndent()
        val k = 6 // kmer length

        val expectedResult = "TGTCGC"
        val result = mostProbableKmer(genome, k, probString)

        assertEquals(expectedResult, result)

    }

    /**
     *  This dataset checks for off-by-one errors at the beginning of Text. Notice that the optimal
    solution (“AGCAGCTT”) occurs at the very beginning of Text, so if your code does not check
    this k-mer, then your code will output a different (incorrect) k-mer as the solution.
     */
    @Test
    @DisplayName("test mostProbableKmer 2")
    fun testMostProbableKmer2() {

        val genome = "AGCAGCTTTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATCTGAACTGGTTACCTGCCGTGAGTAAAT"
        val probString = """
            0.7 0.2 0.1 0.5 0.4 0.3 0.2 0.1
            0.2 0.2 0.5 0.4 0.2 0.3 0.1 0.6
            0.1 0.3 0.2 0.1 0.2 0.1 0.4 0.2
            0.0 0.3 0.2 0.0 0.2 0.3 0.3 0.1
        """.trimIndent()
        val k = 8 // kmer length

        val expectedResult = "AGCAGCTT"
        val result = mostProbableKmer(genome, k, probString)

        assertEquals(expectedResult, result)

    }

    /**
     *  This dataset checks for off-by-one errors at the end of Text. Notice that the optimal
    solution (“AAGCAGAGTTTA”) occurs at the very end of Text, so if your code does not check
    this k-mer, then your code will output a different (incorrect) k-mer as the solution.
     */
    @Test
    @DisplayName("test mostProbableKmer 3")
    fun testMostProbableKmer3() {

        val genome = "TTACCATGGGACCGCTGACTGATTTCTGGCGTCAGCGTGATGCTGGTGTGGATGACATTCCGGTGCGCTTTGTAAGCAGAGTTTA"
        val probString = """
            0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.1 0.2 0.3 0.4 0.5
            0.3 0.2 0.1 0.1 0.2 0.1 0.1 0.4 0.3 0.2 0.2 0.1
            0.2 0.1 0.4 0.3 0.1 0.1 0.1 0.3 0.1 0.1 0.2 0.1
            0.3 0.4 0.1 0.1 0.1 0.1 0.0 0.2 0.4 0.4 0.2 0.3
        """.trimIndent()
        val k = 12 // kmer length

        val expectedResult = "AAGCAGAGTTTA"
        val result = mostProbableKmer(genome, k, probString)

        assertEquals(expectedResult, result)

    }



}