@file:Suppress("SameParameterValue", "UNUSED_VARIABLE")

package problems

/**
 *  1.2 Hidden Messages in the Replication Origin

Code Challenge: Implement PatternCount (reproduced below).
Input: Strings Text and Pattern.
Output: Count(Text, Pattern).

See also:
stepik: https://stepik.org/lesson/240214/step/6?unit=212561
rosalind: http://rosalind.info/problems/ba1a/
 */

fun main() {

//    val genome = "CGATATATCCATAG"
//    val target = "ATA"

    val genome2 = "blahbbbblahblahblahb"
    val target2 = "bb"
    val genome = "TGAGTGCAATGACATGAGTGCAATCCGCGGTCAGTGCAACGGTTACAGTGCAAAAGGACAGTGCAAATAGTGCAAAGTGCAAAGTGCAAAGTGCAAAGTGCAAGAGTGCAAATTTTAGTGCAACGGAGTGCAATAAGATAGTGCAATATGGTAGTGCAAAGTGCAACGGGCGGTTAGTGCAAAGTGCAACGTCCAGTGCAAGAGTGCAATAGTGCAAAGTGCAACCCGAGTGCAAGCGTAAGTGCAAAGTGCAACAGTGCAAGTGCCAAGTGCAACAGTGCAACGAGTGCAACAGTGCAAAGTGCAAAGTGCAATAGTGCAATTAGTGCAACAGTGCAAACAAGTGCAACACTCGAGGGGAGTGCAAAAGTGCAATGTATAGTGCAAAGTGCAAAATAGTGCAAATCATAGAGTGCAAAGTGCAATAGTGCAAAGTGCAAAGTGCAAACGTTCGCGCCTAGTGCAAAGTGAGTGCAACAAGTGCAACAGTGCAATCAGTGCAATGAGTGCAAGAGTACAGATAAGTGCAAATGAGTGCAATAGTGCAAAGTGCAATCCGAGAGTGCAATAGTGCAAAGGCGGCCAAATTGCAAGTGCAAGGGTCTTAGTGCAAAGTGCAACAATTTTGTCCTAGTGCAACAAAGTGCAACAAATAGTGCAAAGTGCAAAGTGCAAAGTGCAAGAGTGCAAAGTGCAATAAGTGCAAGCTCTTTAGTGCAATGAGTGCAACGTGGAAAAGTGCAAAAGTGCAACAAAGTGCAAAGTGCAACAATAGTGCAAAGGTTCAATAGTGCAAAGTGCAACAGTGCAACGAGTGCAACTGGATAGTGCAAGCAGTGCAAAATAGTGCAAACAGTGTACAGTGCAATAGTGCAAAGTGCAATAGTGCAATCAGTGCAAATGAGTGCAAAGTGCAACTAGTGCAAAGTGCAACACGCAGTGCAATAGTGCAACACAGTGCAAAGTGCAACACACGCCGAGTGCAACGAGTGCAAGGAGTGCAAGCGCGGAAGTGCAAAAAGTGCAAAGTGCAAAGTGCAAAGTGCAAAT"
    val target = "AGTGCAAAG"
    println(countRepeatedTargetsWithOverlap(genome, target))
}

fun countRepeatedTargetsWithOverlap(genome: String, target: String): Int {
    var foundCount = 0
    for (i in 0..genome.length-target.length) {
        if (i > target.length + genome.length) {
            break
        }
        if (target == genome.substring(i, i + target.length)) {
            foundCount++
        }
    }
    return foundCount
}